openapi: 3.0.0
info:
  title: Your API
  version: 1.0.0
paths:
  /login:
    post:
      summary: User Login
      description: Endpoint to authenticate and obtain a JWT token.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authentication
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
                  description:
                    type: string
                    description: Details about the error
